# Generated by Django 3.2.7 on 2021-12-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bck1App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
